<a href="https://colab.research.google.com/github/abokill/Abdullah_Alsharqawi-202310739/blob/main/python_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

data_matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("--- Initial Matrix ---\n", data_matrix)

val_3_1 = data_matrix[2][0]
print(f"\n[Task 1] Value at Row 3, Col 1: {val_3_1}")

col_two = data_matrix[:, 1]
print(f"\n[Task 2] Content of the 2nd Column: {col_two}")

element_type = data_matrix.dtype
print(f"\n[Task 3] Array Data Type: {element_type}")

independent_copy = np.copy(data_matrix)
independent_copy[0, 0] = 100
print("\n[Task 4] Modified a deep copy (set index 0,0 to 100)")
print(f"Original matrix remains: {data_matrix[0, 0]}")
print(f"Is original unchanged? {data_matrix[0, 0] != 100}")

linked_view = data_matrix.view()
linked_view[0, 0] = 65
print("\n[Task 5] Modified a view (set index 0,0 to 65)")
print(f"Original matrix now shows: {data_matrix[0, 0]}")
print(f"Did the original change? {data_matrix[0, 0] == 65}")

matrix_dims = data_matrix.shape
print(f"\n[Task 6] Matrix Dimensions (Shape): {matrix_dims}")

print("\n[Task 7] Iterating through elements:")
for (r, c), value in np.ndenumerate(data_matrix):
    print(f"Position ({r}, {c}) contains value: {value}")

extra_data = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
v_combined = np.concatenate((data_matrix, extra_data), axis=0)
h_combined = np.concatenate((data_matrix, extra_data), axis=1)
print("\n[Task 8] Vertical Concatenation:\n", v_combined)
print("Horizontal Concatenation:\n", h_combined)

sub_sections = np.split(data_matrix, 3, axis=1)
print("\n[Task 9] Splitting into 3 column-wise arrays:")
for i, section in enumerate(sub_sections, 1):
    print(f"Section {i}:\n", section)

target_loc = np.argwhere(data_matrix == 60)
print(f"\n[Task 10] Coordinates of value 60: {target_loc}")

row_sorted = np.sort(data_matrix, axis=1)
print("\n[Task 11] Matrix with sorted rows:\n", row_sorted)

high_values = data_matrix[data_matrix > 50]
print(f"\n[Task 12] Elements exceeding 50: {high_values}")

rng = np.random.default_rng()
random_matrix = rng.integers(low=1, high=101, size=(2, 3))
print("\n[Task 13] Random 2x3 Matrix (1-100):\n", random_matrix)

incremented_matrix = np.add(data_matrix, 10)
print("\n[Task 14] Matrix after adding 10 to all elements:\n", incremented_matrix)

--- Initial Matrix ---
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

[Task 1] Value at Row 3, Col 1: 70

[Task 2] Content of the 2nd Column: [20 50 80]

[Task 3] Array Data Type: int64

[Task 4] Modified a deep copy (set index 0,0 to 100)
Original matrix remains: 10
Is original unchanged? True

[Task 5] Modified a view (set index 0,0 to 65)
Original matrix now shows: 65
Did the original change? True

[Task 6] Matrix Dimensions (Shape): (3, 3)

[Task 7] Iterating through elements:
Position (0, 0) contains value: 65
Position (0, 1) contains value: 20
Position (0, 2) contains value: 30
Position (1, 0) contains value: 40
Position (1, 1) contains value: 50
Position (1, 2) contains value: 60
Position (2, 0) contains value: 70
Position (2, 1) contains value: 80
Position (2, 2) contains value: 90

[Task 8] Vertical Concatenation:
 [[65 20 30]
 [40 50 60]
 [70 80 90]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
Horizontal Concatenation:
 [[65 20 30 11 12 13]
 [40 50 60 14 15 16]
 [70 80 90 17 18 19]]

[Task 9